# Generated by Django 4.2.6 on 2023-10-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Inventory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='menu',
            name='No_of_guests',
            field=models.IntegerField(),
        ),
    ]
